name: CI/CD Java API REST

on:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar y ejecutar pruebas con Maven
        run: mvn -B clean verify -f ./pom.xml

      - name: Publicar reportes de pruebas
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
